#ifndef UIMCOMMAND_H
#define UIMCOMMAND_H

enum uimCommand {
    UIMCOMMAND_ACKNOWLEDGE = 0x01,
    UIMCOMMAND_ENABLE_DICE_1 = 0x02,
    UIMCOMMAND_ENABLE_DICE_2 = 0x04,
    UIMCOMMAND_ENABLE_PAWN_SELECTION = 0x08,
    UIMCOMMAND_BLINK = 0x10
};

#endif