#ifndef UIMCOMMAND_H
#define UIMCOMMAND_H

#define UIMCOMMAND_ACKNOWLEDGE 0x01
#define UIMCOMMAND_ENABLE_DICE_1 0x02
#define UIMCOMMAND_ENABLE_DICE_2 0x04
#define UIMCOMMAND_ENABLE_PAWN_SELECTION 0x08
#define UIMCOMMAND_BLINK 0x10

#endif