@startuml componentdiagram
package "Main" {
    cords <-- [PathFinding]

    [motorDriver] <-- cords

    [motorDriver] --> result

    result --> [PathFinding]

    [GameBase] -> gameState

    gameState -> [StorageManager]

    bordState <-- [GameBase]

    [PathFinding] <-- bordState

    [GameBase] --> command

    [I2CHAL] <- command

    response <-- [I2CHAL]

    response -> [GameBase]

    [I2CHAL] --> commando
}

package "UIM" {
    [InputHandler]

    commando --> [I2C HAL]

    
}
@enduml