name: run tests
on:
  - push
permissions:
  contents: read
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: install gtest
        run: sudo apt install -y libgtest-dev
      - name: build
        run: make all_tests
      - name: test motion controller
        run: ./bin/MTG_test_motionController
      - name: generate pathfind debug export
        run: ./bin/MTG_pathfind_debugExport > pathfind.json
      - name: create artafect for debug export
        uses: actions/upload-artifact@v4
        with:
          name: pathfind_export
          path: pathfind.json
