name: run tests
on:
  - push
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: build
        run: make all_tests
      - name: test motion controller
        run: ./bin/MTG_test_motionController
